name: Linting

on:
  pull_request:
  push:
    branches: ["main", "development"]

jobs:
  hlint:
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to GitHub code scanning.
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/hlint-scan@v1


  styling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: haskell-actions/run-fourmolu@v9
      with:
        version: "0.12.0.0"
